source 'http://gems.github.com'
source 'http://rubygems.org'

gem 'rake'
gem 'vpim'
gem 'rspec'
gem 'guard'
gem 'guard-spork', :git => 'https://github.com/irohiroki/guard-spork.git'
gem 'guard-rspec'
gem 'byebug'
